/* This is the main source of data of the handpicked books of this web app and book.js depends on this file
to get access to all the books */

const globalBookRegistry = [
  { mood: 'thrilling', setting: 'future', title: 'Neuromancer', author: 'William Gibson', image: 'https://alexgude.com/books/covers/neuromancer.jpg', desc: 'The ultimate cyberpunk classic. A washed-up computer hacker is hired for one final digital data heist inside a matrix network.' },
  { mood: 'thrilling', setting: 'historical', title: 'The Pillars of the Earth', author: 'Ken Follett', image: 'https://img.sfbook.com/books/large/webp/the-pillars-of-the-earth.webp', desc: 'A high-stakes thriller centered around the building of a grand cathedral amidst betrayal and medieval conspiracies in 12th-century England.' },
  { mood: 'thrilling', setting: 'real', title: 'The Da Vinci Code', author: 'Dan Brown', image: 'https://brennersbooks.cdn.bibliopolis.com/pictures/015295.jpg?auto=webp&v=1715287592', desc: 'A high-speed puzzle-solving race across Paris. Cryptic symbols hidden within classic artworks hold the key to an ancient conspiracy.' },
  { mood: 'thoughtful', setting: 'future', title: 'Dune', author: 'Frank Herbert', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458.jpg', desc: 'A complex sci-fi masterpiece set on a desert planet tracking ecology, deep mental training, and systemic imperial shifts.' },
  { mood: 'thoughtful', setting: 'historical', title: 'The Book Thief', author: 'Markus Zusak', image: 'https://frugalbookstore.net/cdn/shop/products/The_Book_Thief.jpeg?v=1675226877', desc: 'Narrated by Death, this poignant narrative details a young girl holding onto her humanity by rescuing books from destruction in World War II.' },
  { mood: 'thoughtful', setting: 'real', title: 'The Alchemist', author: 'Paulo Coelho', image: 'https://images.gr-assets.com/books/1483412266l/865.jpg', desc: 'An essential allegorical masterpiece. A young shepherd travels from Spain to Egypt looking for treasure, learning to read systemic life signs.' },
  { mood: 'magical', setting: 'future', title: 'The Quantum Thief', author: 'Hannu Rajaniemi', image: 'https://mpd-biblio-covers.imgix.net/9780765375889.jpg', desc: 'A hard sci-fi heist story set in a post-human solar system where magic-like quantum physics rules advanced architectural worlds.' },
  { mood: 'magical', setting: 'historical', title: 'The Way of Kings', author: 'Brandon Sanderson', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1397465050i/11203858.jpg', desc: 'An epic fantasy kingdom layout. Follows separate characters trying to survive a brutal war fueled by ancient magic armor and devastating storms.' },
  { mood: 'magical', setting: 'real', title: 'Harry Potter', author: 'J.K. Rowling', image: 'https://cdn.shopify.com/s/files/1/0674/5433/7265/files/9781546148500_p0.jpg?v=1768970627', desc: 'The iconic urban fantasy where a young boy discovers a hidden parallel magical layout existing directly underneath modern London.' },
  { mood: 'thrilling', setting: 'future', title: 'Altered Carbon', author: 'Richard K. Morgan', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7lP4QBjkK5X15m0oYbHkzMu5CFHDj5FuTYRVVFq8ZmHBEQpn-MZuNzJki&s=10', desc: 'A gritty sci-fi noir where consciousness can be uploaded into new bodies. An elite soldier is downloaded to solve the murder of a billionaire.' },
  { mood: 'thrilling', setting: 'future', title: 'Ready Player One', author: 'Ernest Cline', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1603110684i/35237885.jpg', desc: 'In a bleak future, a teenager hunts for a hidden Easter egg inside a massive virtual reality world that holds a multi-billion dollar fortune.' },
  { mood: 'thrilling', setting: 'historical', title: 'Shōgun', author: 'James Clavell', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1704385704i/52382796.jpg', desc: 'An English sailor is shipwrecked in feudal Japan. He must learn to navigate a brutal, high-stakes web of samurai warlords, political plots, and war.' },
  { mood: 'thrilling', setting: 'historical', title: 'The Alienist', author: 'Caleb Carr', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqHuv88ZxW0t75riM0xMc2f08cfRYed-xQfBQ9rYzFmA&s', desc: 'In 1896 New York City, a psychologist and a reporter use early forensic science and tracking methods to hunt down a brutal criminal.' },
  { mood: 'thrilling', setting: 'real', title: 'Gone Girl', author: 'Gillian Flynn', image: 'https://gilmoreguidetobooks.com/wp-content/uploads/2013/05/gone-girl.png', desc: 'On his fifth wedding anniversary, a man reports that his beautiful wife has vanished, unlocking a dangerous psychological maze of media secrets.' },
  { mood: 'thrilling', setting: 'real', title: 'The Silent Patient', author: 'Alex Michaelides', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1668782119i/40097951.jpg', desc: 'A famous painter shoots her husband and never speaks another word. A criminal psychotherapist becomes obsessed with uncovering her hidden motive.' },
  { mood: 'thoughtful', setting: 'future', title: 'The Left Hand of Darkness', author: 'Ursula K. Le Guin', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1488213612i/18423.jpg', desc: 'A human envoy is sent to an icy, alien world where the inhabitants have no fixed gender, challenging everything he knows about society and culture.' },
  { mood: 'thoughtful', setting: 'future', title: 'Brave New World', author: 'Aldous Huxley', image: 'https://cdn.shopify.com/s/files/1/0674/5433/7265/files/9780060850524_p0.jpg?v=1768984267', desc: 'A haunting look at a highly efficient future society that has traded emotional depth, art, and critical freedom for pure stability and consumer comfort.' },
  { mood: 'thoughtful', setting: 'historical', title: 'Meditations', author: 'Marcus Aurelius', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1691172738i/195589455.jpg', desc: 'The private journal of a Roman Emperor offering deep, timeless insights on stoic philosophy, mental discipline, and navigating reality.' },
  { mood: 'thoughtful', setting: 'historical', title: 'The Name of the Rose', author: 'Umberto Eco', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1415375471i/119073.jpg', desc: 'A brilliant friar investigates a series of mysterious deaths in a 14th-century Italian monastery, examining truth, logic, and forbidden knowledge.' },
  { mood: 'thoughtful', setting: 'real', title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', image: 'https://mpd-biblio-covers.imgix.net/9780374533557.jpg', desc: 'A deep psychological breakdown of human choices, explaining the logic battle between quick intuition and slow, calculated thinking algorithms.' },
  { mood: 'thoughtful', setting: 'real', title: 'Atomic Habits', author: 'James Clear', image: 'https://jamesclear.com/wp-content/uploads/2026/07/atomic-habits-dots.png', desc: 'A highly structural system framework demonstrating how tiny, 1% daily optimizations compound over time into massive personal achievement.' },
  { mood: 'magical', setting: 'future', title: 'Hyperion', author: 'Dan Simmons', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1746983261i/77566.jpg', desc: 'On the eve of galactic war, seven pilgrims travel to a distant world to unlock the supernatural secrets of the mysterious Time Tombs.' },
  { mood: 'magical', setting: 'future', title: 'Lord of Light', author: 'Roger Zelazny', image: 'https://pictures.abebooks.com/inventory/31363104268.jpg', desc: 'On a colony planet, an advanced space crew uses high technology to give themselves the names and supernatural powers of ancient mythical gods.' },
  { mood: 'magical', setting: 'historical', title: 'A Game of Thrones', author: 'George R.R. Martin', image: 'https://i.harperapps.com/hcuk/covers/9780007459483/x450.JPG', desc: 'Noble houses battle for power in a medieval kingdom, completely unaware that an ancient, supernatural force is returning in the icy north.' },
  { mood: 'magical', setting: 'historical', title: 'The Priory of the Orange Tree', author: 'Samantha Shannon', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1700221964i/40275288.jpg', desc: 'An epic fantasy layout tracking an unmarried queen, dragon riders, and hidden mages trying to protect a divided world from a dark threat.' },
  { mood: 'magical', setting: 'real', title: 'The Ocean at the End of the Lane', author: 'Neil Gaiman', image: 'https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1469723638i/25646020.jpg', desc: 'A man returns to his childhood home, unlocking buried memories of an ancient, terrifying magical force that leaked into modern reality.' },
  { mood: 'magical', setting: 'real', title: 'The Night Circus', author: 'Erin Morgenstern', image: 'https://pictures.abebooks.com/inventory/32314425151.jpg', desc: 'A mysterious circus appears only at night. Behind the scenes, two young illusionists are locked in a fierce, high-stakes duel of real magic.' }
];
